Composite action:

- name: Docker Build Tag and Push

inputs:
  username:
    description: Docker login username
    required: true
  password:
    description: Docker login password
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker login
      uses: docker/login-action@v4
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build Docker image
      shell: bash
      run: docker build -f Dockerfile.distroless -t dockerfile-distroless .

    - name : Set Docker tag
      shell: bash
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Tag Docker image
      shell: bash
      run: docker tag dockerfile-distroless ${{ inputs.username }}/nodeapp:$SHORT_SHA

    - name: Push Image
      shell: bash
      run: docker push ${{ inputs.username }}/nodeapp:$SHORT_SHA
