name: Docker CI pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  sonar:
    runs-on: ["wsl-ubuntu-pvk"]

    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -f Dockerfile.distroless -t distroless .

      - name: Tag and Push Docker Image
        run: |
          SHA=${GITHUB_SHA::7}
          docker tag distroless ${{ vars.DOCKERHUB_USERNAME }}/nodeapp7:$SHA
          docker push ${{ vars.DOCKERHUB_USERNAME }}/nodeapp7:$SHA
          
